# Generated by Django 3.0.6 on 2021-01-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.CharField(max_length=255)),
                ('side', models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center')], max_length=16)),
                ('temperature', models.FloatField()),
                ('error', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
