# Generated by Django 3.0.6 on 2021-01-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.CharField(help_text='The user session ID', max_length=255)),
                ('side', models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center')], help_text='The side the photo was taken', max_length=16)),
                ('temperature', models.FloatField(help_text='The estimated center temperature')),
                ('error', models.BooleanField(default=False, help_text='Whether an error occurred or not during photo acquisition')),
                ('image', models.ImageField(help_text='The acquired image', upload_to='')),
                ('colormap', models.SmallIntegerField(blank=True, choices=[(-1, 'None'), (11, 'Hot'), (2, 'Jet'), (8, 'Cool'), (9, 'HSV'), (7, 'Spring'), (1, 'Bone')], default=-1, help_text='Colormap name used when saving the image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
