##
# Restart gunicorn and nginx
##

- name: restart gunicorn
  service:
    name: '{{ gunicorn_name }}.service'
    state: restarted
    enabled: yes
  become: yes

- name: restart nginx
  service:
    name: nginx
    state: restarted
    enabled: yes
  become: yes

